apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
  labels:
    app: nestjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs-container
          image: ecr-image
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /service/ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 2